In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2021-03-19 18:32:29--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  55.4MB/s    in 3.6s    

2021-03-19 18:32:32 (48.3 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2021-03-19 18:32:32--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  27.0MB/s    in 2.3s    

2021-03-19 18:32:35 (27.0 MB/s) - ‘test_32x32.mat’ saved [64275384/64

In [ ]:
import keras
from keras.layers.normalization import BatchNormalization
import numpy as np
import scipy.io as io
from keras.layers import Activation, Flatten,Softmax
from keras.layers import Conv2D
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import MaxPooling2D
from keras.models import Sequential
from keras import optimizers
from keras.backend import function
import pandas as pd

In [ ]:
from keras.backend import function

In [ ]:
#importing data
train_set = io.loadmat("train_32x32.mat")
test_set = io.loadmat("test_32x32.mat")
x_train = train_set['X']
y_train = train_set['y']
x_test = test_set['X']
y_test = test_set['y']
# Reshaping test and training data sets
x_train = np.moveaxis(x_train,[3,0,1,2],[0,1,2,3])
x_train = x_train.astype('float32')
x_test = np.moveaxis(x_test,[3,0,1,2],[0,1,2,3])
x_test = np.asarray(x_test)
x_test = x_test.astype('float32')
#Normalisation des données
x_train /= x_train.max()
x_test /= x_test.max()
# Passage de classe comme integer à classe comme vecteur de dimension classes
y_test_RN = [y-1 for y in y_test]# la classe 1 corresponds au array qui à 1 en indice 0
y_train_RN = [y-1 for y in y_train]
classes = 10
y_train_RN = keras.utils.to_categorical(y_train_RN, classes)
y_test_RN = keras.utils.to_categorical(y_test_RN, classes)
 #Définition du type de data pour optimiser la mémoire
y_train_RN = y_train_RN.astype('int32')
y_test_RN = y_test_RN.astype('int32')
# Featurewise normalization
datagen = keras.preprocessing.image.ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    horizontal_flip=False,
    zca_whitening=False, 
    zca_epsilon=1e-06)

datagen.fit(x_train)

In [ ]:
from google.colab import drive
drive.mount('drive')

Mounted at drive


In [ ]:
model = keras.models.load_model('/content/drive/My Drive/Projet 3A')

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 32, 32, 64)        1792      
_________________________________________________________________
S1 (MaxPooling2D)            (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 14, 14, 128)       73856     
_________________________________________________________________
S2 (MaxPooling2D)            (None, 7, 7, 128)         0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 5, 5, 128)         147584    
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 3, 3, 128)         147584    
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 1, 1, 128)        

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
y_test_KNN=[k.item() for k in y_test]
y_train_KNN=[k.item() for k in y_train]

In [ ]:
get_conv50_output = function([model.layers[0].input],
                                  [model.layers[6].output])
layer_output_conv50 = get_conv50_output([x_train[:10000]])
conv50=np.array(layer_output_conv50[0]).reshape(10000,128)
knn1=KNeighborsClassifier()
knn1.fit(conv50,y_train_KNN[:10000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
get_conv50_output = function([model.layers[0].input],
                                  [model.layers[6].output])
layer_output_conv50 = get_conv50_output([x_train[10000:20000]])
conv501=np.array(layer_output_conv50[0]).reshape(10000,128)
knn2=KNeighborsClassifier()
knn2.fit(conv501,y_train_KNN[10000:20000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
layer_output_conv50 = get_conv50_output([x_train[20000:30000]])
conv502=np.array(layer_output_conv50[0]).reshape(10000,128)
knn3=KNeighborsClassifier()
knn3.fit(conv502,y_train_KNN[20000:30000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
layer_output_conv50 = get_conv50_output([x_train[30000:40000]])
conv503=np.array(layer_output_conv50[0]).reshape(10000,128)
knn4=KNeighborsClassifier()
knn4.fit(conv503,y_train_KNN[30000:40000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
layer_output_conv50 = get_conv50_output([x_train[40000:50000]])
conv504=np.array(layer_output_conv50[0]).reshape(10000,128)
knn5=KNeighborsClassifier()
knn5.fit(conv504,y_train_KNN[40000:50000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
layer_output_conv50 = get_conv50_output([x_train[50000:60000]])
conv505=np.array(layer_output_conv50[0]).reshape(10000,128)
knn6=KNeighborsClassifier()
knn6.fit(conv504,y_train_KNN[50000:60000])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
layer_output_conv50_test = get_conv50_output([x_test[:5000]])

In [ ]:
conv50_test=np.array(layer_output_conv50_test[0]).reshape(5000,128)

In [ ]:
Y1=knn1.predict(conv50_test)
Y1

array([5, 2, 1, ..., 2, 4, 9])

In [ ]:
Y2=knn2.predict(conv50_test)
Y2

array([5, 2, 1, ..., 2, 4, 9])

In [ ]:
Y3=knn3.predict(conv50_test)
Y3

array([5, 2, 1, ..., 2, 4, 9])

In [ ]:
Y4=knn4.predict(conv50_test)
Y4

array([5, 2, 1, ..., 2, 4, 9])

In [ ]:
Y5=knn5.predict(conv50_test)
Y5

array([5, 2, 1, ..., 2, 4, 9])

In [ ]:
Y6=knn6.predict(conv50_test)
Y6

array([3, 1, 1, ..., 2, 2, 5])

In [ ]:
from collections import Counter

In [ ]:
right=0
for i in range(5000):
  P=[Y1[i],Y2[i],Y3[i],Y4[i],Y5[i]]
  c=Counter(P).most_common(1)[0][0]
  if c==y_test_KNN[i]:
    right=right+1

In [ ]:
right

4589